services:
  db:
    container_name: db  
    image: postgres:15-alpine
    volumes:
      - ./postgres/data:/var/lib/postgressql/data
    
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
    expose:
      - 5432

    restart: always
  backend:
    build: 
      context: .
      dockerfile: dockerfiles/dev/django/Dockerfile
    container_name: fahimweb
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes :
      - ./core:/usr/src/app
      - static_volumes:/usr/src/app/staticfiles
      - media_volumes:/usr/src/app/media

    depends_on:
      - db
    expose:
      - "8000"
    environment:
      - SECRET_KEY=text
      - DEBUG=False

    
  nginx:
    container_name: nginx
    image: nginx
    ports:
    - "8080:80"

    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volumes:/usr/src/app/staticfiles
      - media_volumes:/usr/src/app/media

    depends_on:
      - db
      - backend
    
volumes:
  static_volumes:
  media_volumes: