# Generated by Django 4.2.17 on 2025-01-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={},
        ),
    ]
