# Generated by Django 4.2.17 on 2025-01-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_newslettersubscriber_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ['-subscribed_date']},
        ),
    ]
