# Generated by Django 4.2.17 on 2025-01-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Gender',
            new_name='gender',
        ),
    ]
