# Generated by Django 4.2.17 on 2024-12-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='breif_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
