# Generated by Django 4.2.17 on 2024-12-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productmodel_discount_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='breif_description',
            new_name='brief_description',
        ),
    ]
