# Generated by Django 4.2.17 on 2025-02-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_favoritesproductmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritesproductmodel',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='favoritesproductmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='favoritesproductmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
