# Generated by Django 4.2.17 on 2025-02-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_favoritesproductmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='avg_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
