# Generated by Django 4.2.17 on 2025-02-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_ordermodel_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ['-created_date']},
        ),
    ]
