# Generated by Django 4.2.17 on 2025-02-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='avg_rate',
        ),
    ]
