# Generated by Django 4.2.17 on 2025-02-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_reviewmodel_avg_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار تایید خرید'), (2, 'خرید تایید شده'), (3, 'خرید رد شده')], default=1),
        ),
    ]
